weights: ''
cfg: yolov4-csp.yaml
data: data/vials.yaml
hyp: data/hyp.scratch.yaml
epochs: 50
batch_size: 16
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
name: yolov4-csp-orig-test
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
total_batch_size: 16
world_size: 1
global_rank: -1
